export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const GET_USER = 'GET_USER'
export const REPORT_POST = 'REPORT_POST'
export const DECLINE_REPORT = 'DECLINE_REPORT'
export const GIVE_LIKE = 'GIVE_LIKE'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS'
export const REMOVE_SOUND = 'REMOVE_SOUND'
export const CONFIRM_REPORT = 'CONFIRM_REPORT'
export const FOLLOW_USER = 'FOLLOW_USER'
export const EDIT_DESCRIPTION = 'EDIT_DESCRIPTION'
export const STOP_FOLLOW = 'STOP_FOLLOW'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'

export const CHANGE_INFO_REQUEST = 'CHANGE_INFO_REQUEST'
export const CHANGE_INFO_SUCCESS = 'CHANGE_INFO_SUCCESS'
export const CHANGE_INFO_FAILURE = 'CHANGE_INFO_FAILURE'

export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE'

export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE'

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'

export const ADD_PHOTO_REQUEST = 'ADD_PHOTO_REQUEST'
export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS'
export const ADD_PHOTO_FAILURE = 'ADD_PHOTO_FAILURE'

export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE'

export const GEN_SOUNDSCAPE_REQUEST = 'GEN_SOUNDSCAPE_REQUEST'
export const GEN_SOUNDSCAPE_SUCCESS = 'GEN_SOUNDSCAPE_SUCCESS'
export const GEN_SOUNDSCAPE_FAILURE = 'GEN_SOUNDSCAPE_FAILURE'
