/**
 * @module MutationTypes
 * 
 * @description En este fichero se encuentran las macros correspondientes con cada uno de los tipos de mutaciones que existen en el sistema
 */

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const REPORT_POST_SUCCESS = 'REPORT_POST_SUCCESS'
export const REPORT_POST_FAILURE = 'REPORT_POST_FAILURE'

export const DECLINE_REPORT_SUCCESS = 'DECLINE_REPORT_SUCCESS'
export const DECLINE_REPORT_FAILURE = 'DECLINE_REPORT_FAILURE'

export const GIVE_LIKE_SUCCESS = 'GIVE_LIKE_SUCCESS'
export const GIVE_LIKE_FAILURE = 'GIVE_LIKE_FAILURE'

export const REMOVE_LIKE_SUCCESS = 'REMOVE_LIKE_SUCCESS'
export const REMOVE_LIKE_FAILURE = 'REMOVE_LIKE_FAILURE'

export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS'
export const REMOVE_POST_FAILURE = 'REMOVE_POST_FAILURE'

export const REMOVE_SOUND_SUCCESS = 'REMOVE_SOUND_SUCCESS'
export const REMOVE_SOUND_FAILURE = 'REMOVE_SOUND_FAILURE'

export const CONFIRM_REPORT_SUCCESS = 'CONFIRM_REPORT_SUCCESS'
export const CONFIRM_REPORT_FAILURE = 'CONFIRM_REPORT_FAILURE'

export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'
export const FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE'

export const EDIT_DESCRIPTION_SUCCESS = 'EDIT_DESCRIPTION_SUCCESS'
export const EDIT_DESCRIPTION_FAILURE = 'EDIT_DESCRIPTION_FAILURE'

export const STOP_FOLLOW_SUCCESS = 'STOP_FOLLOW_SUCCESS'
export const STOP_FOLLOW_FAILURE = 'STOP_FOLLOW_FAILURE'

export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS'
export const REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE'

export const CHANGE_INFO_SUCCESS = 'CHANGE_INFO_SUCCESS'
export const CHANGE_INFO_FAILURE = 'CHANGE_INFO_FAILURE'

export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE'

export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE'

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'

export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS'
export const ADD_PHOTO_FAILURE = 'ADD_PHOTO_FAILURE'

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE'

export const GEN_SOUNDSCAPE_REQUEST = 'GEN_SOUNDSCAPE_REQUEST'
export const GEN_SOUNDSCAPE_SUCCESS = 'GEN_SOUNDSCAPE_SUCCESS'
export const GEN_SOUNDSCAPE_FAILURE = 'GEN_SOUNDSCAPE_FAILURE'

export const GET_OTHERUSER_SUCCESS = 'GEN_OTHERUSER_SUCCESS'
export const GET_OTHERUSER_FAILURE = 'GET_OTHERUSER_FAILURE'
